ARG CUDA_VER=10.2
FROM nvidia/cuda:${CUDA_VER}-devel-ubuntu18.04

RUN apt update && apt install -y \
    git \
    libcap2 \
    lsb-release \
    perl \
    python \
    sudo \
    wget \
    && \
    rm -rf /var/lib/apt/lists/*

ARG CUDA_VER=10.2
ENV CUDA_HOME=/usr/local/cuda-${CUDA_VER}/

ENV MLNX_OFED_VERSION=5.0-2.1.8.0
ENV MOFED_DIR=MLNX_OFED_LINUX-${MLNX_OFED_VERSION}-ubuntu18.04-x86_64
ENV MOFED_SITE_PLACE=MLNX_OFED-${MLNX_OFED_VERSION}
ENV MOFED_IMAGE=MLNX_OFED_LINUX-${MLNX_OFED_VERSION}-ubuntu18.04-x86_64.tgz
RUN wget --no-verbose http://content.mellanox.com/ofed/${MOFED_SITE_PLACE}/${MOFED_IMAGE} && \
    tar -xzvf ${MOFED_IMAGE} && \
    ${MOFED_DIR}/mlnxofedinstall \
        --user-space-only \
        --without-fw-update \
        --all \
        -q \
        --skip-distro-check \
        --force \
        && \
    cd .. && \
    rm -rf ${MOFED_DIR} && \
    rm -rf *.tgz

# Install HPC-X
ENV HPCX_DOCKER_INSTALL_DIR="/opt/hpcx"
ENV HPCX_PACKAGE_NAME="hpcx-v2.6.0-gcc-MLNX_OFED_LINUX-5.0-1.0.0.0-ubuntu18.04-x86_64"
#ENV HPCX_PACKAGE_NAME="hpcx-v2.6.1-gcc-MLNX_OFED_LINUX-5.0-2.1.8.1.7-ubuntu18.04-x86_64"
ENV HPCX_PACKAGE_DOWNLOAD_URL="http://www.mellanox.com/downloads/hpc/hpc-x/v2.6/${HPCX_PACKAGE_NAME}.tbz"
#ENV HPCX_PACKAGE_DOWNLOAD_URL="http://hpcweb.lab.mtl.com/hpc/noarch/HPCX/v2.6.1/2020-05-17/${HPCX_PACKAGE_NAME}.tbz"
RUN echo "INFO: Install HPC-X..."
RUN mkdir -p ${HPCX_DOCKER_INSTALL_DIR}
RUN cd ${HPCX_DOCKER_INSTALL_DIR} && \
    wget --no-verbose ${HPCX_PACKAGE_DOWNLOAD_URL} && \
    tar xfj ${HPCX_PACKAGE_NAME}.tbz && \
    rm -f ${HPCX_PACKAGE_NAME}.tbz
RUN echo "INFO: Install HPC-X... DONE"

ENV PATH="${HPCX_DOCKER_INSTALL_DIR}/${HPCX_PACKAGE_NAME}/ompi/bin:${HPCX_DOCKER_INSTALL_DIR}/${HPCX_PACKAGE_NAME}/sharp/bin:${PATH}"
ENV LD_LIBRARY_PATH="${HPCX_DOCKER_INSTALL_DIR}/${HPCX_PACKAGE_NAME}/ompi/lib:${HPCX_DOCKER_INSTALL_DIR}/${HPCX_PACKAGE_NAME}/sharp/lib:${HPCX_DOCKER_INSTALL_DIR}/${HPCX_PACKAGE_NAME}/nccl_rdma_sharp_plugin/lib:${HPCX_DOCKER_INSTALL_DIR}/${HPCX_PACKAGE_NAME}/ucx/lib:${LD_LIBRARY_PATH}"
ENV HPCX_DIR="${HPCX_DOCKER_INSTALL_DIR}/${HPCX_PACKAGE_NAME}"
ENV OPAL_PREFIX="${HPCX_DOCKER_INSTALL_DIR}/${HPCX_PACKAGE_NAME}/ompi"
