ARG CUDA_VER=10.2
FROM nvidia/cuda:${CUDA_VER}-devel-ubuntu18.04

# DEBIAN_FRONTEND=noninteractive needed to avoid interactive questions during tzdata (installed as a dependency) installation
RUN apt update && DEBIAN_FRONTEND=noninteractive apt install -y \
    environment-modules \
    git \
    g++ \
    make \
    rsync \
    tcl \
    && \
    rm -rf /var/lib/apt/lists/*

ENV MLNX_OFED_VERSION=5.0-2.1.8.0
ENV MOFED_DIR MLNX_OFED_LINUX-${MLNX_OFED_VERSION}-ubuntu18.04-x86_64
ENV MOFED_SITE_PLACE MLNX_OFED-${MLNX_OFED_VERSION}
ENV MOFED_IMAGE MLNX_OFED_LINUX-${MLNX_OFED_VERSION}-ubuntu18.04-x86_64.iso
RUN wget --no-verbose http://content.mellanox.com/ofed/${MOFED_SITE_PLACE}/${MOFED_IMAGE} && \
    tar -xzvf ${MOFED_IMAGE} && \
    ${MOFED_DIR}/mlnxofedinstall --user-space-only --without-fw-update --all -q --force && \
    cd .. && \
    rm -rf ${MOFED_DIR} && \
    rm -rf *.tgz
